title: Tycoon Phishing Kit OAuth Application Impersonation
status: stable
description: |
  Detects indicators of compromise (IOCs) and suspicious OAuth consent activity 
  linked to the Tycoon/ODx phishing kits. These campaigns impersonate Microsoft 
  OAuth apps to bypass MFA and harvest Microsoft 365 credentials.
references:
  - >-
    https://rhisac.org/threat-intelligence/microsoft-oauth-app-impersonation-leads-to-mfa-phishing/
author: Aryan, Detections.ai, GPT-5
date: 2025-08-16T00:00:00.000Z
tags:
  - attack.initial_access
  - attack.credential_access
  - attack.defense_evasion
  - attack.t1566
  - attack.t1528
  - attack.t1111
  - attack.t1078
  - attack.t1071.001
  - attack.t1556.003
  - platform.azure
  - platform.office365
  - platform.saas
  - category.phishing
  - category.oauth_abuse
  - category.cloud_identity
  - product.azure
  - product.azuread
  - product.microsoft365
logsource:
  category: proxy
  product: azure
detection:
  selection_app_id:
    AppId:
      - 14b2864e-3cff-4d33-b5cd-7f14ca272ea4
      - 85da47ec-2977-40ab-af03-f3d45aaab169
      - 355d1228-1537-4e90-80a6-dae111bb4d70
      - 6628b5b8-55af-42b4-9797-5cd5c148313c
      - b0d8ea55-bc29-436c-9f8b-f8829030261d
      - 22c606e8-7d68-4a09-89d9-c3c563a453a0
      - 31c6b531-dd95-4361-93df-f5a9c906da39
      - 055399fa-29b9-46ab-994d-4ae06f40bada
      - 6a77659d-dd6f-4c73-a555-aed25926a05f
      - 21f81c9e-475d-4c26-9308-1de74a286f73
      - 987c259f-da29-4575-8072-96c610204830
      - db2eb385-c02f-44fc-b204-ade7d9f418b1
      - f99a0806-7650-4d78-acef-71e445dfc844
      - fdcf7337-92bf-4c70-9888-ea234b6ffb0d
      - fe0e32ca-d09e-4f80-af3c-5b086d4b8e66
  selection_domains:
    destination.domain|re:
      - (?i)azureapplicationregistration\.(pages\.dev|com|net)
      - (?i)yrqwvevbjcfv\..*
      - (?i)gmlygt\..*
      - (?i)pw5\.haykovx\..*
      - (?i)chikeukohandco\.com
  selection_ip:
    destination.ip:
      - 2a00:b703:fff2:35::1
  selection_user_agent:
    http.user_agent|contains:
      - axios/1.7.9
      - axios/1.8.2
  selection_oauth_consent:
    OperationName|contains: Consent to application
  condition: >
    selection_app_id or ( selection_oauth_consent and ( selection_domains or
    selection_ip or selection_user_agent ) ) or ( 2 of ( selection_domains,
    selection_ip, selection_user_agent ) )
falsepositives:
  - Legitimate apps may use Axios user agents.
  - Some listed domains may later be cleaned and reused.
  - Investigate before blocking — confirm via OAuth consent logs and user
    context.
level: high
